# Website settings
url: "https://chuhaojin.github.io/"

# Internal nav
nav:
  main:
  writing:

# Bio settings
name: "Chuhao Jin"
description: "The home page of Chuhao Jin."
thumbnail_path: "profile-photos/Chuhao Jin - medium.jpg"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/chuhao-jin-995a97181/"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/chuhaojin/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:jinchuhao@ruc.edu.cn"
    label: "Email"
    value: "jinchuhao@ruc.edu.cn"
    icon: "envelope-square"

# chuhao build settings
paginate: 20
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: brikis98/yevgeniy-brikman-homepage

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
